///////////////////////////////////////////////////////////
//  WorkFlow_Entities.cs
//  Implementation of the Class WorkFlow_Entities
//  Generated by Enterprise Architect
//  Created on:      13-11月-2015 14:05:13
//  Original author: Chenbin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;



namespace FlowEngine.Modals {
	public enum WE_STATUS : int {ACTIVE, SUSPEND, CREATED, DONE, DELETED, INVALID}
	public class WorkFlow_Entity {

		public WorkFlow_Entity(){

		}

		~WorkFlow_Entity(){

		}

		/// <summary>
		/// 工作流实体ID 主键
		/// </summary>
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]        
        public int WE_Id{
			get;
			set;
		}

        /// <summary>
        /// 工作流编号 YYYYMMXXXX
        /// </summary>
        public string WE_Ser { get; set; }
		/// <summary>
		/// 与之联系的WorkFlow
		/// </summary>
		public virtual WorkFlow_Define WE_Wref{
			get;
			set;
		}

		/// <summary>
		/// 工作流实体的状态
		/// </summary>
		public WE_STATUS WE_Status{
			get;
			set;
		}

        /// <summary>
        /// 工作流实体的二进制动态信息
        /// </summary>
        public byte[] WE_Binary
        {
            get;
            set;
        }

		/// <summary>
		/// 该实体的运行相关信息
		/// </summary>
		public virtual ICollection<Mission> Process_Info{
			get;
			set;
		}

        /// <summary>
        /// 实体的当前事件 2016/5/16
        /// </summary>
        public virtual ICollection<CURR_Mission> Curr_Mission
        {
            get;
            set;
        }

        /// <summary>
        /// 实体状态迁移的最后时间
        /// </summary>
        public DateTime? Last_Trans_Time
        {
            get;
            set;
        }

	}//end WorkFlow_Entity//end WorkFlow_Entities

}//end namespace FlowEngine.Modals