///////////////////////////////////////////////////////////
//  BaseDAO.cs
//  Implementation of the Class BaseDAO
//  Generated by Enterprise Architect
//  Created on:      13-11ÔÂ-2015 14:40:41
//  Original author: Chenbin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using FlowEngine.Modals;



namespace FlowEngine.DAL {
	public class BaseDAO {

		public BaseDAO(){

		}

		~BaseDAO(){

		}

		protected FlowEngine.Modals.WorkFlowContext NewDB(){

            return new WorkFlowContext();
		}

	}//end BaseDAO

}//end namespace FlowEngine.DAL