///////////////////////////////////////////////////////////
//  Mission.cs
//  Implementation of the Class Mission
//  Generated by Enterprise Architect
//  Created on:      13-11月-2015 20:40:36
//  Original author: Chenbin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;



namespace FlowEngine.Modals {
	/// <summary>
	/// 任务表，记录了已处理的工作
	/// </summary>
	public class Mission {

		public Mission(){

		}

		~Mission(){

		}

		/// <summary>
		/// 主键
		/// </summary>
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]        
        public int Miss_Id{
			get;
			set;
		}		

		/// <summary>
		/// 创建任务任务的事件名称
		/// </summary>
		public string Event_Name{
			get;
			set;
		}

        /// <summary>
        /// 任务的名称
        /// </summary>
        public string Miss_Name { get; set; }

        /// <summary>
        /// 任务的描述
        /// </summary>
        public string Miss_Desc { get; set; }

		/// <summary>
		/// 任务所属工作流实体
		/// </summary>
		public virtual WorkFlow_Entity Miss_WFentity{
			get;
			set;
		}

        /// <summary>
        /// 该任务的前一任务
        /// </summary>    
        
        public virtual Mission pre_Mission
        {
            get;
            set;
        }

        /// <summary>
        /// 该任务的后一任务
        /// </summary> 
        public virtual ICollection<Mission> next_Mission
        {
            get;
            set;
        }

        /// <summary>
        /// 任务包含的Record数据
        /// </summary>
        public virtual ICollection<Process_Record> Record_Info
        {
            get;
            set;
        }

        /// <summary>
        /// 任务包含的参数值
        /// </summary>
        public virtual ICollection<Mission_Param> Params_Info
        {
            get;
            set;
        }
	}//end Mission

}//end namespace FlowEngine.Modals