///////////////////////////////////////////////////////////
//  Process_Record.cs
//  Implementation of the Class Process_Record
//  Generated by Enterprise Architect
//  Created on:      13-11月-2015 20:25:07
//  Original author: Chenbin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FlowEngine.Modals;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace FlowEngine.Modals {
	/// <summary>
	/// 工作流实体工作记录，如，用户id，时间，等 需要说明的是，为了保证工作流引擎模块与具体业务的独立性，
	/// 在此并不定义具体的信息类型，需要用户根据具体业务应用指定
	/// </summary>
	public class Process_Record {

		public Process_Record(){

		}

		~Process_Record(){

		}

		/// <summary>
		/// 记录ID，主键
		/// </summary>
		[Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
		public int Re_Id{
			get;
			set;
		}

		/// <summary>
		/// 记录的名称：如，用户ID， 时间等
		/// </summary>
		public string Re_Name{
			get;
			set;
		}

		/// <summary>
		/// 记录的值， 如果若 Info_Name 为时间， 则该字段可以为 2015/11/2 19:30:00
		/// </summary>
		public string Re_Value{
			get;
			set;
		}

        /// <summary>
        /// 记录所属的Mission
        /// </summary>
        public virtual Mission Re_Mission { get; set; }

	}//end Process_Record

}//end namespace FlowEngine.Modals