///////////////////////////////////////////////////////////
//  WorkFlow_Define.cs
//  Implementation of the Class WorkFlow_Define
//  Generated by Enterprise Architect
//  Created on:      13-11月-2015 14:05:13
//  Original author: Chenbin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;



namespace FlowEngine.Modals {
	/// <summary>
	/// 工作流的定义
	/// </summary>
	public class WorkFlow_Define {

		public WorkFlow_Define(){

		}

		~WorkFlow_Define(){

		}

		/// <summary>
		/// 工作流描述
		/// </summary>
		public string W_Attribution{
			get;
			set;
		}

		/// <summary>
		/// 主键
		/// </summary>
		[Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
		public int W_ID{
			get;
			set;
		}

		/// <summary>
		/// 工作流名称
		/// </summary>
		public string W_Name{
			get;
			set;
		}

		/// <summary>
		/// 由该工作流创建的实体列表
		/// </summary>
		public virtual ICollection<WorkFlow_Entity> W_Wentities{
			get;
			set;
		}

		/// <summary>
		/// 工作流的XML描述文档
		/// </summary>
		public byte[] W_Xml{
			get;
			set;
		}

	}//end WorkFlow_Define

}//end namespace FlowEngine.Modals