///////////////////////////////////////////////////////////
//  CFlow.cs
//  Implementation of the Class CFlow
//  Generated by Enterprise Architect
//  Created on:      28-10月-2015 13:57:50
//  Original author: chenbin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FlowEngine;
using FlowEngine.Flow;
namespace FlowEngine.Flow {
	public class CFlow : IXMLEntity, IFlow {

		/// <summary>
		/// 流（Flow）的目的事件（Event）
		/// </summary>
		private string m_DestEvent = "";
		/// <summary>
		/// 流程（Flow）的条件表达式
		/// </summary>
		private string m_expression = "";
		/// <summary>
		/// 流（Flow）的源事件
		/// </summary>
		private string m_SourceEvent = "";

		public CFlow(){

		}

		~CFlow(){

		}

		/// <summary>
		/// 获得/设置流程（Flow）的目的事件
		/// </summary>
		public string destination_event{
			get;
			set;
		}

		/// <summary>
		/// 计算流（Flow）表达式的值
		/// 返回值：真假
		/// </summary>
		public bool Evaluate(){

			return false;
		}

		/// <summary>
		/// 获取/设置流（Flow）表达式
		/// </summary>
		public string expression{
			get;
			set;
		}

		/// <summary>
		/// 解析XML元素
		/// </summary>
		/// <param name="xmlNode"></param>
		public void InstFromXmlNode(XmlNode xmlNode){

		}

		/// <summary>
		/// 获得/设置流程（Flow）的源事件（Event）的名称
		/// </summary>
		public string source_event{
			get;
			set;
		}

		/// <summary>
		/// 反解析到XML元素
		/// </summary>
		public XmlNode WriteToXmlNode(){

			return null;
		}

	}//end CFlow

}//end namespace Flow