///////////////////////////////////////////////////////////
//  CSymbol.cs
//  Implementation of the Class CSymbol
//  Generated by Enterprise Architect
//  Created on:      28-10月-2015 14:59:32
//  Original author: chenbin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FlowEngine.Flow {
	/// <summary>
	/// 标识符
	/// </summary>
	public class CSymbol {
		/// <summary>
		/// 名称
		/// </summary>
		private string m_name;
		/// <summary>
		/// 类型
		/// </summary>
		private CSymbol.Type m_type;
		/// <summary>
		/// 值
		/// </summary>
		private object m_value;

        public enum Type : int
        {
            Param,
            Value,
            Operator,
            Function,
            Result,
            OpenBracket,
            CloseBracket,
            Invalid //未知，非法
        };

		public CSymbol(){

		}

		~CSymbol(){

		}

		public string name{
			get{
				return m_name;
			}
			set{
				m_name = value;
			}
		}

		/// <summary>
		/// 类型
		/// </summary>
		public Type type{
			get{
				return m_type;
			}
			set{
				m_type = value;
			}
		}

		/// <summary>
		/// 值
		/// </summary>
		public object value{
			get{
				return m_value;
			}
			set{
				m_value = value;
			}
		}

		public override string ToString(){

            return name;
		}

	}

}//end namespace Flow