///////////////////////////////////////////////////////////
//  IXMLEntity.cs
//  Implementation of the Interface IXMLEntity
//  Generated by Enterprise Architect
//  Created on:      26-10月-2015 9:46:30
//  Original author: Ailibuli
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Xml;



namespace FlowEngine {
	/// <summary>
	/// 对象实体的XML解析及生成的接口
	/// </summary>
	public interface IXMLEntity     {

		/// <summary>
		/// 解析XML元素
		/// </summary>
		/// <param name="xmlNode"></param>
		void InstFromXmlNode (XmlNode xmlNode);

		/// <summary>
		/// 反解析到XML元素
		/// </summary>
		XmlNode WriteToXmlNode();
	}//end IXMLEntity

}//end namespace FlowEngine