///////////////////////////////////////////////////////////
//  CCombEvent.cs
//  Implementation of the Class CCombEvent
//  Generated by Enterprise Architect
//  Created on:      26-10月-2015 9:46:30
//  Original author: chenbin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FlowEngine.Event;
using FlowEngine;
using System.Xml;
namespace FlowEngine.Event {
	public class CCombEvent : CEvent {

		private List<CNormlEvent> m_parlevents = new List<CNormlEvent>();

		public CCombEvent(CWorkFlow parent) : base(parent) {

		}

		~CCombEvent(){

		}

		/// <summary>
		/// 解析XML元素
		/// </summary>
		/// <param name="xmlNode"></param>
		public override void InstFromXmlNode(XmlNode xmlNode){
            //1. 解析基类CEvent的成员
            base.InstFromXmlNode(xmlNode);

            //2. 解析CombEvent的成员

		}

		/// <summary>
		/// 反解析到XML元素
		/// </summary>
		public override XmlNode WriteToXmlNode(){

            //1. 反解析基类部分成员
            XmlNode xn = base.WriteToXmlNode();

            //2. 反解析CombEvent的成员
            XmlElement xe = (XmlElement)xn;
            xe.SetAttribute("type", "combevent");
            return xn;
		}

		/// <summary>
		/// 进入该事件（Event）
		/// </summary>
		/// <param name="strjson"></param>
		public override void EnterEvent(string strjson){

		}

		/// <summary>
		/// 离开该事件（Event）
		/// </summary>
		/// <param name="strjson"></param>
		public override void LeaveEvent(string strjson){

		}

	}//end CCombEvent

}//end namespace Event