// <auto-generated />
namespace FlowEngine.Modals.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class modify1207 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modify1207));
        
        string IMigrationMetadata.Id
        {
            get { return "201612071248062_modify1207"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
